Use acpi_ec to run under secure boot mode or a lockdowned kernel
Signed-off-by: Hollow Man <hollowman@opensuse.org>

diff --git a/nitrosense b/nitrosense
--- a/nitrosense
+++ b/nitrosense
@@ -1,7 +1,6 @@
 #!/bin/bash
 
 if [ $# -le 0 ]; then
-	echo "ENA: [w]rite to ec"
 	echo "PWR: [q]uiet [d]efault [p]erformance"
 	echo "FAN: [a]uto  [c]ustom  [m]ax"
 	echo "DBG: [r]ead from ec"
@@ -10,21 +9,14 @@ if [ $# -le 0 ]; then
 	exit
 fi
 
-echo on | sudo tee /sys/module/msr/parameters/allow_writes &>/dev/null
+EC=/dev/ec
 
-if [[ "$(lsmod | grep ec_sys | cut -f1 -d' ' | tr -d '\n' | wc -c)" -ne 6 ]]; then
-	sudo rmmod ec_sys
-	if [ -f ~/ec_sys.ko ]; then
-		if ! sudo insmod ~/ec_sys.ko write_support=1; then
-			sudo dmesg | tail
-			exit
-		fi
-	else
-		sudo modprobe ec_sys write_support=1
-	fi
+if [[ ! -c "$EC" ]]; then
+	echo "EC not found at $EC!"
+    echo "please install the kernel module 'acpi_ec' first and then reboot."
+	echo "Check https://github.com/MusiKid/acpi_ec?tab=readme-ov-file#installation"
+	exit 1
 fi
-
-EC=/sys/kernel/debug/ec/ec0/io
 
 if [[ $* =~ "r" ]]; then
 	if [[ $(sudo ls $EC 2>/dev/null) ]]; then
@@ -41,19 +33,6 @@ function ecw() {
 	printf "$2" | sudo dd of=$EC bs=1 seek="$1" count=1 conv=notrunc &>/dev/null
 }
 
-function set_power_limits() {
-	MSR=/sys/devices/virtual/powercap/intel-rapl/intel-rapl:0
-	MCH=/sys/devices/virtual/powercap/intel-rapl-mmio/intel-rapl-mmio:0
-	for N in "$MSR" "$MCH"; do
-		echo "${1}000000" | sudo tee "$N/constraint_0_power_limit_uw" &>/dev/null
-		echo "${2}000000" | sudo tee "$N/constraint_1_power_limit_uw" &>/dev/null
-		echo "128000000"  | sudo tee "$N/constraint_0_time_window_us" &>/dev/null
-		echo "128000000"  | sudo tee "$N/constraint_1_time_window_us" &>/dev/null
-		[[ "$N" == "$MSR" ]] && NODE=MSR || NODE=MCH
-		echo "[$NODE] PL1 [$(cat "$N/constraint_0_power_limit_uw") $(cat "$N/constraint_0_time_window_us")] PL2 [$(cat "$N/constraint_1_power_limit_uw") $(cat "$N/constraint_1_time_window_us")]"
-	done
-}
-
 ecw $((0x03)) '\x11' # Write-Enable
 
 if [[ $(sudo ls $EC 2>/dev/null) ]]; then
@@ -61,19 +40,16 @@ if [[ $(sudo ls $EC 2>/dev/null) ]]; then
 		echo "PWR - Quiet"
 		ecw $((0x2c)) '\x00' # 00 01 04 PWR: quiet default perf
 		ecw $((0x2d)) '\x04' # 04 05 PWR
-		set_power_limits 10 15
 	fi
 	if [[ $* =~ "d" ]]; then
 		echo "PWR - Default"
 		ecw $((0x2c)) '\x01' # 00 01 04 PWR: quiet default perf
 		ecw $((0x2d)) '\x04' # 04 05 PWR
-		set_power_limits 45 75
 	fi
 	if [[ $* =~ "p" ]]; then
 		echo "PWR - Performance"
 		ecw $((0x2c)) '\x04' # 00 01 04 PWR: quiet default perf
 		ecw $((0x2d)) '\x04' # 04 05 PWR
-		set_power_limits 75 95
 	fi
 	if [[ $* =~ "n" ]]; then
 		echo "PWR - nvidia-powerd restart"
